version: '3'

services:
  www:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/:ro
    environment:
      TZ: Asia/Tokyo

  db:
    image: mysql:5.7-debian
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: icloudprivaterelayipuser
      MYSQL_PASSWORD: icloudprivaterelayip#PW
      MYSQL_DATABASE: icloudprivaterelayip
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 
